### ISSUE TITLE
Please share ubuntu, Debian, aarchlinux rootfs

### ISSUE THREAD

**Issue by Saikatsaha1996** [zongou/proot-tool#2]
Any rootfs given me this error 
![Screenshot_2024-08-14-16-11-56-64_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/63274b22-dd4d-4973-934c-6c06d35e60b6)

**Comment by zongou** [comment]
You can exlude dev dir with --exclude option, for example
```sh
xz -d <noble-server-cloudimg-arm64-root.tar.xz | ./prootie/prootie.sh install [rootfs] --exclude="dev"
```
When this is done, do
```sh
touch ~/home/.hushlogin
```
can suppress login warnings.

I will append option '--exclude="dev"' in program soon.

**Comment by zongou** [comment]
Sorry i missed the tittle,
If you want more rootfs
try
```sh
apt install -y gum
./tmp/prootie_tui.sh
```

**Comment by Saikatsaha1996** [comment]
> Sorry i missed the tittle, If you want more rootfs try
> 
> ```shell
> apt install -y gum
> ./tmp/prootie_tui.sh
> ```

Working.. but how to access tmp dir ?

```
root@localhost:~# vkmark
error: XDG_RUNTIME_DIR is invalid or not set in the environment.
Error: Failed to find usable window system, try using --winsys-dir
```

Solved 

```
prootie login ./distros/ubuntu-noble-default -b $PREFIX/tmp:/tmp -b /sdcard:/sdcard
```

**Comment by Saikatsaha1996** [comment]
@zongou any fix ?

![Screenshot_2024-08-25-16-53-16-99_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/812ac4cf-9e65-4fef-8111-9af5ecd99177)

**Comment by zongou** [comment]
> @zongou any fix ?
> 
> ![Screenshot_2024-08-25-16-53-16-99_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/812ac4cf-9e65-4fef-8111-9af5ecd99177)
> 
It is fixed.
